apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "shop-backend.fullname" . }}-cronjob
  labels:
    {{- include "shop-backend.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Values.cronjob.name }}
              image: {{ .Values.cronjob.image }}
              command:
                {{ .Values.cronjob.command | toJson }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
